package engine

const ReportTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoVult Security Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        .glass { background: rgba(255, 255, 255, 0.05); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.1); }
        body { background-color: #0d1117; color: #c9d1d9; font-family: 'Inter', sans-serif; }
    </style>
</head>
<body class="p-8">
    <div class="max-w-6xl mx-auto">
        <header class="mb-12 flex justify-between items-center">
            <div>
                <h1 class="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">GoVult</h1>
                <p class="text-gray-400 mt-2">Vulnerability Assessment Report</p>
            </div>
            <div class="text-right">
                <p class="text-xs text-gray-500">Scan Time: {{.ScanTime}}</p>
                <span class="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-xs font-bold border border-emerald-500/20">v2.0 Master Edition</span>
            </div>
        </header>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
            <div class="glass p-6 rounded-2xl">
                <h3 class="text-gray-400 text-sm mb-1">Total Vulnerabilities</h3>
                <p class="text-3xl font-bold text-white">{{len .Findings}}</p>
            </div>
            <div class="glass p-6 rounded-2xl">
                <h3 class="text-gray-400 text-sm mb-1">Target Scanned</h3>
                <p class="text-xl font-bold text-blue-400 truncate">{{.Target}}</p>
            </div>
            <div class="glass p-6 rounded-2xl">
                <h3 class="text-gray-400 text-sm mb-1">Risk Score</h3>
                <p class="text-3xl font-bold text-red-500">{{.RiskScore}} / 10</p>
            </div>
        </div>

        <div class="glass rounded-2xl overflow-hidden">
            <table class="w-full text-left">
                <thead class="bg-white/5 border-b border-white/10">
                    <tr>
                        <th class="p-4 text-xs font-bold uppercase text-gray-400">ID</th>
                        <th class="p-4 text-xs font-bold uppercase text-gray-400">Severity</th>
                        <th class="p-4 text-xs font-bold uppercase text-gray-400">Target URL</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-white/10">
                    {{range .Findings}}
                    <tr class="hover:bg-white/5 transition-colors">
                        <td class="p-4 font-mono text-sm text-gray-300">{{.TemplateID}}</td>
                        <td class="p-4">
                            <span class="px-2 py-0.5 rounded text-[10px] font-bold uppercase {{if eq .Severity "critical"}}bg-red-500/20 text-red-400{{else if eq .Severity "high"}}bg-orange-500/20 text-orange-400{{else}}bg-blue-500/20 text-blue-400{{end}}">
                                {{.Severity}}
                            </span>
                        </td>
                        <td class="p-4 font-mono text-sm text-gray-400 break-all">{{.Target}}</td>
                    </tr>
                    {{end}}
                </tbody>
            </table>
        </div>

        <footer class="mt-12 text-center text-gray-600 text-xs">
            Generated by GoVult &copy; 2026. All rights reserved.
        </footer>
    </div>
</body>
</html>
`
